cmake_minimum_required(VERSION 3.31)
project(assignment)

set(CMAKE_CXX_STANDARD 20)

add_subdirectory(assignment02)
add_subdirectory(assignment03)
add_subdirectory(assignment04)
add_subdirectory(assignment05)
add_subdirectory(assignment07)
add_subdirectory(assignment08)
add_subdirectory(assignment09)