cmake_minimum_required(VERSION 3.31)
project(LAB3_practice)

set(CMAKE_CXX_STANDARD 20)

add_subdirectory(LAB3_61)
add_subdirectory(LAB3_62)
add_subdirectory(LAB3_63)
add_subdirectory(LAB3_64)
add_subdirectory(LAB3_71)
add_subdirectory(LAB3_72)
add_subdirectory(LAB3_81)
add_subdirectory(LAB3_82)
add_subdirectory(assignment06_LAB3_83)
